### ISSUE TITLE
Support  2021 and 2022 language updates ? 

### ISSUE THREAD

**Issue by jbdavid5027** [bmarkovic17/nestedtext#1]
Hi boris , there have been some changes to  nestedText syntax since the original release.. specifically in v2.0 (2021) and V3.0 .. 
Perhaps you can add support for the changes . specifically related to trailing commas in lists and quoted dictionary keys., 
thanks

**Comment by bmarkovic17** [comment]
Hi Jonathan, I've been planning to do this for quite some time, but becoming a parent took away all my free time (and energy :)), so I kinda put this task on hold. I'm gonna try to work on this in the upcoming weeks.

**Comment by KenKundert** [comment]
Good luck Boris.  Let me know when you are finished and I will update your entry on nestedtext.org.

**Comment by bmarkovic17** [comment]
I've just published a new version of the extension that supports NestedText v3.0.
So far I've done some basic testing, but I'll be testing it more thoroughly in the following days and fix some issues if I find them. Feel free to open a new issue in case you notice something isn't working as it should.

@KenKundert I've noticed on your [related projects documentation page](https://nestedtext.org/en/stable/related_projects.html) that this project is named _visual studio_, while it actually is an extension for _Visual Studio Code_. That is different from Visual Studio which is an IDE, while Visual Studio Code is a lightweight code editor. It would be great if you could update this also with the version. Thanks.

**Comment by jbdavid5027** [comment]
Sure.  I did that once. The free time eventually comes back.  Do let me
know if there are ways I can help . At the moment I have no experience with
developing extentions for vscode, but some good ideas on what I think they
should do for me.  Some python, perl and tons of SystemVerilog experience.
