### ISSUE TITLE
Error hilighting a : that is part of a value

### ISSUE THREAD

**Issue by p-i-** [bmarkovic17/nestedtext#3]
```
some_key: |
    quick brown
    fox: jumps
```

The `fox: jumps` line gets hilit, even though it is part of the value-string.

**Comment by p-i-** [comment]
<img width="140" alt="Screenshot 2024-05-08 at 12 56 26" src="https://github.com/bmarkovic17/nestedtext/assets/693495/df1e3d2e-dcbb-4a77-a322-9ead6cf39d6e">

**Comment by bmarkovic17** [comment]
I believe your example refers to the [YAML](https://yaml.org/spec/1.2.2/#23-scalars) way of handling multiline strings.

In [NestedText](https://nestedtext.org/en/stable/basic_syntax.html#strings) multiline strings are adjacent lines that start with a string tag (greater-than symbol) followed by a space or newline:

```
some_key:
    > quick brown
    > fox: jumps
```

which produces the correct syntax highlighting

![image](https://github.com/bmarkovic17/nestedtext/assets/13367265/fe61b94d-0dde-4422-aeaa-c2ea04116fd9)
