### ISSUE TITLE
Multiline value (using `|` or `>`) containing blank line incorrectly hilit

### ISSUE THREAD

**Issue by p-i-** [bmarkovic17/nestedtext#4]
<img width="162" alt="Screenshot 2024-05-08 at 13 22 43" src="https://github.com/bmarkovic17/nestedtext/assets/693495/19993423-97be-4792-b1fa-fe3ae99e05bb">

**Comment by bmarkovic17** [comment]
Basically the same thing as this [issue](https://github.com/bmarkovic17/nestedtext/issues/3).

The correct way to use multiline strings is

```
prompt:
    > part1
    >
    > part2
```

which produces the correct syntax highlighting:

![image](https://github.com/bmarkovic17/nestedtext/assets/13367265/b822a851-e480-4a4d-9293-60fa65da0e88)
